---
- name: add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: limits.yml
- include: login_defs.yml
- include: minimize_access.yml
- include: pam.yml
- include: profile.yml
- include: securetty.yml
- include: suid_sgid.yml
- include: sysctl.yml
- include: yum.yml
