---
- name: remove unused repositories
  file: name='/etc/yum.repos.d/{{item}}.repo' state=absent
  with_items:
    - 'CentOS-Debuginfo'
    - 'CentOS-Media'
    - 'CentOS-Vault'
  when: os_security_packages_clean

- name: activate gpg-check for yum-repos
  shell: "sed -i 's/gpgcheck=0/gpgcheck=1/g' {{item}}"
  with_items:
    - '/etc/yum.conf'
    - '/etc/yum.repos.d/*.repo'

- name: activate gpg-check for yum rhn if it exists
  shell: sed -i 's/gpgcheck=0/gpgcheck=1/g' /etc/yum/pluginconf.d/rhnplugin.conf removes='/etc/yum/pluginconf.d/rhnplugin.conf'

- name: remove packages
  yum: name='{{item}}' state=removed
  with_items:
    - xinetd
    - inetd
    - ypserv
    - telnet-server
    - rsh-server
  when: os_security_packages_clean
